---
name: POE-Component-WWW-PastebinCom-Retrieve
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: non-blocking wrapper around WWW::PastebinCom::Retrieve
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Filter::Line: 1.2222
  POE::Filter::Reference: 1.222
  POE::Wheel::Run: 1.2222
  WWW::PastebinCom::Retrieve: 0.002
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::PastebinCom::Retrieve:
    file: lib/POE/Component/WWW/PastebinCom/Retrieve.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
